version: "2"

networks:
  test:

services:
  reputationServer:
    container_name: reputationServer
    image: python-memcached
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_test
    working_dir: /home
    command: sleep 60000
    volumes:
      - ../scripts:/home/scripts
    ports:
      - 5555:5555
    networks:
      - test
